### ISSUE TITLE
Make it possible to unlink shared sensors that are shared with you

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#20]
Removing manually shared sensors on mobile apps should remove the sharing information for good.

**Comment by Muhwu** [comment]
`unshare` end-point (target oneself + sensor id) now does this.

Nothing currently prevents resharing, tho. There is also a soft delete option, but this would block resharing unless we add an "unblock" option to the app. I guess it could be a separate *block* list rather than "unshare" / "unlink" - and that list could exist.

If this becomes a problem that is. We still have the soft delete flag, which we could edit in the database if a single user had a problem with someone sharing a tag. This would also block manual unsharing, so it functions as a block.
