### ISSUE TITLE
How to return high frequent data + pruned data (question)

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-network-serverless#28]
This issue is to discuss about if it would be better to return only one type of data in one request or if the server should return a data blob that may be a mix of different frequency data...

Let's say, user's plan allows 1 day high freq data and 3 months low freq data, should a single api request of 3 day data return 1 day data with more data points per hour (for example 1 data point per 5 min) and 2 days of pruned data (let's say 1 datapoint per 1 h). To me this would make sense because this way on the mobile app side it would not be needed to know details of what kind of plan user has...

**Comment by Muhwu** [comment]
On that note, would you be selecting and updating the plan through the mobile app or does that happen separately?

I would think that when the user logs in on the mobile app, it would sync the subscription information either way.

From an API perspective, I think it would be _cleaner_ to have it return uniform data, but I see your point as well. It just depends on which side we want to do it. By always returning the _highest resolution possible_ we take away the option to return the sparse version and if we want to visualize with uniform data distribution, we'd have to do this on the client side (say you want your "year in review" type of data visualization).

A third alternative is to have an additional parameter, something like `format` that determines whether the returned data frequency will be `high`, `low` or `both` - or something to that extent. This is a bit more logic on the API side but gives more flexibility. The behavior could be so that with `high`, it returns the subscription worth of data even if your date range is measured in years.

**Comment by laurijamsa** [comment]
Subscriptions and top-ups are coming later (free plan only in the beginning) and we are still considering the best way to handle them.

The mobile apps are built so that they don't really care about how often sensors give data to be appended data on the local database because Bluetooth background scanning has been a pain in the arse as some phones scan nearby Bluetooth broadcast messages better than others.

Mostly why I'm suggesting this is because I think it would mean less headache on the mobile app side as the Network would be responsible of returning correct kind of data and that's it. We're also planning to have a web UI later and that would mean that we'd need to implement this logic to 4 different places (Network, Android app, iOS app, webUI app) instead of just trusting that network always returns data that has been defined on the subscription plan.

Other question: is it currently possible to request lower frequency data than what subscription allows? Meaning, can the app request let's say 1 datapoint per day of the last 365 days even if subscription level would allow to request 24 points a day of the last 365 days?

**Comment by Muhwu** [comment]
This hasn't been implemented currently so the allowed frequencies are static. Once we settle on the requirements, we can think of an implementation path. One way to implement it would be to, for example, scan the sparse table and just calculate it on the fly. Looping through 8760 data point for one year to reduce it to 365.

Amazon Timestream potentially would have more of this type of functionality out of the box, but it'd take quite a bit of effort to switch the database at this point. Not impossible if dynamo turns out to be too rigid.

**Comment by ojousima** [comment]
I think this was implemented in data modes of sparse and dense data? Is #96 related?

**Comment by Muhwu** [comment]
Yup.
